# Generated by Django 3.2.4 on 2021-07-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210704_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.CharField(default='Name', max_length=30, verbose_name='Students name'),
        ),
    ]
