# Generated by Django 3.2.4 on 2021-07-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_answer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30, verbose_name='User Name')),
                ('comment', models.CharField(max_length=255, verbose_name='Comment')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(default='Name', max_length=30, verbose_name='Quiz Taker'),
        ),
    ]
